version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dbbudgetninja
    ports:
      - 5435:5432
    volumes:
      - dbbudgetninja_data:/var/lib/postgresql/data

volumes:
  dbbudgetninja_data: